# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_App(object):
    def setupUi(self, App):
        App.setObjectName("App")
        App.resize(300, 400)
        App.setMaximumSize(QtCore.QSize(300, 400))
        App.setStyleSheet("background-color: rgb(39, 39, 39);")
        self.b = QtWidgets.QComboBox(App)
        self.b.setGeometry(QtCore.QRect(60, 60, 151, 22))
        self.b.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(0, 0, 0);")
        self.b.setObjectName("b")
        self.pushButton = QtWidgets.QPushButton(App)
        self.pushButton.setGeometry(QtCore.QRect(100, 290, 75, 23))
        self.pushButton.setStyleSheet("background-color: rgb(255, 85, 0);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(App)
        QtCore.QMetaObject.connectSlotsByName(App)

    def retranslateUi(self, App):
        _translate = QtCore.QCoreApplication.translate
        App.setWindowTitle(_translate("App", "Form"))
        self.pushButton.setText(_translate("App", "PushButton"))
